//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Stock_ManagementEntities : DbContext
    {
        public Stock_ManagementEntities()
            : base("name=Stock_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<productInStock> productInStocks { get; set; }
        public virtual DbSet<Shelt> Shelts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbShopeeInfo> tbShopeeInfoes { get; set; }
        public virtual DbSet<tbTikTokInfo> tbTikTokInfoes { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
