//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productInStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productInStock()
        {
            this.types = new HashSet<type>();
        }
    
        public int id { get; set; }
        public string industry_group { get; set; }
        public string industry { get; set; }
        public string group { get; set; }
        public Nullable<int> type_product { get; set; }
        public string sku { get; set; }
        public string name_Product { get; set; }
        public string Name_Branch { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Shelf { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Shelt Shelt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<type> types { get; set; }
    }
}
