//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string SKU_Product { get; set; }
        public string QR_SKU { get; set; }
        public string Name_Product { get; set; }
        public Nullable<int> Id_Shelf { get; set; }
    
        public virtual Shelt Shelt { get; set; }
    }
}
