//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbShopeeInfo
    {
        public int id { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string classificationCode { get; set; }
        public string classificationName { get; set; }
        public string SKUProduct { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
