//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTikTokInfo
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string product_name { get; set; }
        public string sku_id { get; set; }
        public string variation_value { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string seller_sku { get; set; }
    }
}
