#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerment
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Stock_Management")]
	public partial class StockDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertproductInStock(productInStock instance);
    partial void UpdateproductInStock(productInStock instance);
    partial void DeleteproductInStock(productInStock instance);
    partial void InserttbShopeeInfo(tbShopeeInfo instance);
    partial void UpdatetbShopeeInfo(tbShopeeInfo instance);
    partial void DeletetbShopeeInfo(tbShopeeInfo instance);
    partial void InserttbTikTokInfo(tbTikTokInfo instance);
    partial void UpdatetbTikTokInfo(tbTikTokInfo instance);
    partial void DeletetbTikTokInfo(tbTikTokInfo instance);
    #endregion
		
		public StockDataContext() : 
				base(global::StockManagerment.Properties.Settings.Default.Stock_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<productInStock> productInStocks
		{
			get
			{
				return this.GetTable<productInStock>();
			}
		}
		
		public System.Data.Linq.Table<tbShopeeInfo> tbShopeeInfos
		{
			get
			{
				return this.GetTable<tbShopeeInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbTikTokInfo> tbTikTokInfos
		{
			get
			{
				return this.GetTable<tbTikTokInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productInStock")]
	public partial class productInStock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _industry_group;
		
		private string _industry;
		
		private string _group;
		
		private System.Nullable<int> _type_product;
		
		private string _sku;
		
		private string _name_Product;
		
		private string _Name_Branch;
		
		private System.Nullable<double> _Price;
		
		private System.Nullable<int> _Shelf;
		
		private System.Nullable<int> _Stock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onindustry_groupChanging(string value);
    partial void Onindustry_groupChanged();
    partial void OnindustryChanging(string value);
    partial void OnindustryChanged();
    partial void OngroupChanging(string value);
    partial void OngroupChanged();
    partial void Ontype_productChanging(System.Nullable<int> value);
    partial void Ontype_productChanged();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void Onname_ProductChanging(string value);
    partial void Onname_ProductChanged();
    partial void OnName_BranchChanging(string value);
    partial void OnName_BranchChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    partial void OnShelfChanging(System.Nullable<int> value);
    partial void OnShelfChanged();
    partial void OnStockChanging(System.Nullable<int> value);
    partial void OnStockChanged();
    #endregion
		
		public productInStock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_industry_group", DbType="NVarChar(150)")]
		public string industry_group
		{
			get
			{
				return this._industry_group;
			}
			set
			{
				if ((this._industry_group != value))
				{
					this.Onindustry_groupChanging(value);
					this.SendPropertyChanging();
					this._industry_group = value;
					this.SendPropertyChanged("industry_group");
					this.Onindustry_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_industry", DbType="NVarChar(150)")]
		public string industry
		{
			get
			{
				return this._industry;
			}
			set
			{
				if ((this._industry != value))
				{
					this.OnindustryChanging(value);
					this.SendPropertyChanging();
					this._industry = value;
					this.SendPropertyChanged("industry");
					this.OnindustryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[group]", Storage="_group", DbType="NVarChar(150)")]
		public string group
		{
			get
			{
				return this._group;
			}
			set
			{
				if ((this._group != value))
				{
					this.OngroupChanging(value);
					this.SendPropertyChanging();
					this._group = value;
					this.SendPropertyChanged("group");
					this.OngroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_product", DbType="Int")]
		public System.Nullable<int> type_product
		{
			get
			{
				return this._type_product;
			}
			set
			{
				if ((this._type_product != value))
				{
					this.Ontype_productChanging(value);
					this.SendPropertyChanging();
					this._type_product = value;
					this.SendPropertyChanged("type_product");
					this.Ontype_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="NVarChar(50)")]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_Product", DbType="NVarChar(200)")]
		public string name_Product
		{
			get
			{
				return this._name_Product;
			}
			set
			{
				if ((this._name_Product != value))
				{
					this.Onname_ProductChanging(value);
					this.SendPropertyChanging();
					this._name_Product = value;
					this.SendPropertyChanged("name_Product");
					this.Onname_ProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Branch", DbType="NVarChar(200)")]
		public string Name_Branch
		{
			get
			{
				return this._Name_Branch;
			}
			set
			{
				if ((this._Name_Branch != value))
				{
					this.OnName_BranchChanging(value);
					this.SendPropertyChanging();
					this._Name_Branch = value;
					this.SendPropertyChanged("Name_Branch");
					this.OnName_BranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shelf", DbType="Int")]
		public System.Nullable<int> Shelf
		{
			get
			{
				return this._Shelf;
			}
			set
			{
				if ((this._Shelf != value))
				{
					this.OnShelfChanging(value);
					this.SendPropertyChanging();
					this._Shelf = value;
					this.SendPropertyChanged("Shelf");
					this.OnShelfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbShopeeInfo")]
	public partial class tbShopeeInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _productCode;
		
		private string _productName;
		
		private string _classificationCode;
		
		private string _classificationName;
		
		private string _SKUProduct;
		
		private string _SKU;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnproductCodeChanging(string value);
    partial void OnproductCodeChanged();
    partial void OnproductNameChanging(string value);
    partial void OnproductNameChanged();
    partial void OnclassificationCodeChanging(string value);
    partial void OnclassificationCodeChanged();
    partial void OnclassificationNameChanging(string value);
    partial void OnclassificationNameChanged();
    partial void OnSKUProductChanging(string value);
    partial void OnSKUProductChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    #endregion
		
		public tbShopeeInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productCode", DbType="NVarChar(50)")]
		public string productCode
		{
			get
			{
				return this._productCode;
			}
			set
			{
				if ((this._productCode != value))
				{
					this.OnproductCodeChanging(value);
					this.SendPropertyChanging();
					this._productCode = value;
					this.SendPropertyChanged("productCode");
					this.OnproductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="NVarChar(150)")]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this.OnproductNameChanging(value);
					this.SendPropertyChanging();
					this._productName = value;
					this.SendPropertyChanged("productName");
					this.OnproductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classificationCode", DbType="NVarChar(50)")]
		public string classificationCode
		{
			get
			{
				return this._classificationCode;
			}
			set
			{
				if ((this._classificationCode != value))
				{
					this.OnclassificationCodeChanging(value);
					this.SendPropertyChanging();
					this._classificationCode = value;
					this.SendPropertyChanged("classificationCode");
					this.OnclassificationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classificationName", DbType="NVarChar(150)")]
		public string classificationName
		{
			get
			{
				return this._classificationName;
			}
			set
			{
				if ((this._classificationName != value))
				{
					this.OnclassificationNameChanging(value);
					this.SendPropertyChanging();
					this._classificationName = value;
					this.SendPropertyChanged("classificationName");
					this.OnclassificationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKUProduct", DbType="NVarChar(50)")]
		public string SKUProduct
		{
			get
			{
				return this._SKUProduct;
			}
			set
			{
				if ((this._SKUProduct != value))
				{
					this.OnSKUProductChanging(value);
					this.SendPropertyChanging();
					this._SKUProduct = value;
					this.SendPropertyChanged("SKUProduct");
					this.OnSKUProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NVarChar(50)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTikTokInfo")]
	public partial class tbTikTokInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _product_id;
		
		private string _product_name;
		
		private string _sku_id;
		
		private string _variation_value;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<int> _quantity;
		
		private string _seller_sku;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onsku_idChanging(string value);
    partial void Onsku_idChanged();
    partial void Onvariation_valueChanging(string value);
    partial void Onvariation_valueChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void Onseller_skuChanging(string value);
    partial void Onseller_skuChanged();
    #endregion
		
		public tbTikTokInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="NVarChar(50)")]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(50)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku_id", DbType="NVarChar(50)")]
		public string sku_id
		{
			get
			{
				return this._sku_id;
			}
			set
			{
				if ((this._sku_id != value))
				{
					this.Onsku_idChanging(value);
					this.SendPropertyChanging();
					this._sku_id = value;
					this.SendPropertyChanged("sku_id");
					this.Onsku_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_variation_value", DbType="NVarChar(50)")]
		public string variation_value
		{
			get
			{
				return this._variation_value;
			}
			set
			{
				if ((this._variation_value != value))
				{
					this.Onvariation_valueChanging(value);
					this.SendPropertyChanging();
					this._variation_value = value;
					this.SendPropertyChanged("variation_value");
					this.Onvariation_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seller_sku", DbType="NVarChar(20)")]
		public string seller_sku
		{
			get
			{
				return this._seller_sku;
			}
			set
			{
				if ((this._seller_sku != value))
				{
					this.Onseller_skuChanging(value);
					this.SendPropertyChanging();
					this._seller_sku = value;
					this.SendPropertyChanged("seller_sku");
					this.Onseller_skuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
